# Comprehensive Wireshark display filters for advanced network analysis
# Based on Wireshark's built-in display filter reference

COMMON_FILTERS = {
    "Operators": [
        "==", "!=", ">", ">=", "<", "<=",
        "and", "or", "xor", "not",
        "contains", "matches", "in", "~",
        "bitwise_and", "&",
    ],
    "Frame": [
        "frame.number", "frame.time", "frame.time_epoch", "frame.time_delta",
        "frame.time_relative", "frame.len", "frame.cap_len", "frame.marked",
        "frame.ignored", "frame.protocols", "frame.coloring_rule.name",
        "frame.offset_shift", "frame.time_delta_displayed",
    ],
    "Ethernet": [
        "eth.addr", "eth.src", "eth.dst", "eth.type", "eth.len",
        "eth.lg", "eth.ig", "eth.multicast", "eth.broadcast",
        "eth.fcs", "eth.fcs_good", "eth.fcs_bad",
        "eth.trailer", "eth.padding",
    ],
    "ARP": [
        "arp", "arp.opcode", "arp.hw.type", "arp.proto.type",
        "arp.hw.size", "arp.proto.size",
        "arp.src.hw_mac", "arp.src.proto_ipv4",
        "arp.dst.hw_mac", "arp.dst.proto_ipv4",
        "arp.duplicate-address-detected", "arp.duplicate-address-frame",
    ],
    "VLAN": [
        "vlan", "vlan.id", "vlan.priority", "vlan.cfi", "vlan.etype",
        "vlan.len", "vlan.trailer", "vlan.too_many_tags",
    ],
    "IP": [
        "ip", "ip.version", "ip.hdr_len", "ip.dsfield", "ip.dsfield.dscp",
        "ip.dsfield.ecn", "ip.len", "ip.id", "ip.flags", "ip.flags.rb",
        "ip.flags.df", "ip.flags.mf", "ip.frag_offset", "ip.ttl",
        "ip.proto", "ip.checksum", "ip.checksum_bad", "ip.checksum_good",
        "ip.src", "ip.dst", "ip.addr", "ip.src_host", "ip.dst_host",
        "ip.host", "ip.fragment", "ip.fragment.overlap",
        "ip.fragment.toolongfragment", "ip.fragment.error",
        "ip.fragment.count", "ip.reassembled_in", "ip.reassembled.length",
        "ip.geoip.src_country", "ip.geoip.dst_country",
        "ip.geoip.src_city", "ip.geoip.dst_city",
    ],
    "IPv6": [
        "ipv6", "ipv6.version", "ipv6.tclass", "ipv6.tclass.dscp",
        "ipv6.tclass.ecn", "ipv6.flow", "ipv6.plen", "ipv6.nxt",
        "ipv6.hlim", "ipv6.src", "ipv6.dst", "ipv6.addr",
        "ipv6.src_host", "ipv6.dst_host", "ipv6.host",
        "ipv6.fragment", "ipv6.fragment.offset", "ipv6.fragment.more",
        "ipv6.fragment.id", "ipv6.reassembled_in",
        "ipv6.geoip.src_country", "ipv6.geoip.dst_country",
    ],
    "ICMP": [
        "icmp", "icmp.type", "icmp.code", "icmp.checksum",
        "icmp.checksum_bad", "icmp.ident", "icmp.seq", "icmp.seq_le",
        "icmp.data_time", "icmp.data_time_relative",
        "icmp.resptime", "icmp.no_resp",
    ],
    "ICMPv6": [
        "icmpv6", "icmpv6.type", "icmpv6.code", "icmpv6.checksum",
        "icmpv6.checksum_bad", "icmpv6.length", "icmpv6.data",
        "icmpv6.nd.ns.target_address", "icmpv6.nd.na.target_address",
        "icmpv6.nd.ra.router_lifetime", "icmpv6.nd.ra.reachable_time",
        "icmpv6.opt.type", "icmpv6.opt.length",
    ],
    "TCP": [
        "tcp", "tcp.srcport", "tcp.dstport", "tcp.port",
        "tcp.stream", "tcp.len", "tcp.seq", "tcp.seq_raw",
        "tcp.nxtseq", "tcp.ack", "tcp.ack_raw", "tcp.hdr_len",
        "tcp.flags", "tcp.flags.res", "tcp.flags.ns", "tcp.flags.cwr",
        "tcp.flags.ecn", "tcp.flags.urg", "tcp.flags.ack", "tcp.flags.push",
        "tcp.flags.reset", "tcp.flags.syn", "tcp.flags.fin",
        "tcp.window_size", "tcp.window_size_value", "tcp.window_size_scalefactor",
        "tcp.checksum", "tcp.checksum_bad", "tcp.checksum_good",
        "tcp.urgent_pointer", "tcp.options", "tcp.options.mss",
        "tcp.options.wscale", "tcp.options.sack_perm", "tcp.options.sack",
        "tcp.options.timestamp.tsval", "tcp.options.timestamp.tsecr",
        "tcp.time_delta", "tcp.time_relative",
        "tcp.analysis.flags", "tcp.analysis.bytes_in_flight",
        "tcp.analysis.push_bytes_sent", "tcp.analysis.acks_frame",
        "tcp.analysis.ack_rtt", "tcp.analysis.initial_rtt",
        "tcp.analysis.out_of_order", "tcp.analysis.reused_ports",
        "tcp.analysis.retransmission", "tcp.analysis.fast_retransmission",
        "tcp.analysis.duplicate_ack", "tcp.analysis.duplicate_ack_num",
        "tcp.analysis.zero_window", "tcp.analysis.zero_window_probe",
        "tcp.analysis.zero_window_probe_ack", "tcp.analysis.keep_alive",
        "tcp.analysis.keep_alive_ack", "tcp.reassembled_in",
        "tcp.reassembled.length", "tcp.segment", "tcp.segment.overlap",
        "tcp.segment.overlap.conflict", "tcp.segment.multiple_tails",
        "tcp.segment.too_long_fragment", "tcp.segment.error",
        "tcp.segment.count", "tcp.urgent_pointer",
    ],
    "UDP": [
        "udp", "udp.srcport", "udp.dstport", "udp.port",
        "udp.length", "udp.checksum", "udp.checksum_bad",
        "udp.checksum_good", "udp.checksum_coverage",
        "udp.stream", "udp.time_delta", "udp.time_relative",
    ],
    "HTTP": [
        "http", "http.request", "http.response", "http.request.method",
        "http.request.uri", "http.request.version", "http.request.full_uri",
        "http.response.code", "http.response.phrase", "http.response.version",
        "http.host", "http.user_agent", "http.referer", "http.cookie",
        "http.set_cookie", "http.authorization", "http.www_authenticate",
        "http.content_type", "http.content_length", "http.content_encoding",
        "http.transfer_encoding", "http.location", "http.server",
        "http.connection", "http.accept", "http.accept_encoding",
        "http.accept_language", "http.cache_control", "http.date",
        "http.last_modified", "http.expires", "http.etag",
        "http.if_modified_since", "http.if_none_match",
        "http.request_in", "http.response_in", "http.time",
        "http.request.line", "http.response.line",
        "http.file_data", "http.content_length_header",
    ],
    "HTTPS/TLS": [
        "tls", "ssl", "tls.handshake.type", "tls.record.version",
        "tls.record.length", "tls.handshake.version", "tls.handshake.random",
        "tls.handshake.session_id", "tls.handshake.cipher_suite",
        "tls.handshake.compression_method", "tls.handshake.extension.type",
        "tls.handshake.extensions_server_name", "tls.handshake.certificate",
        "tls.alert.level", "tls.alert.description", "tls.app_data",
        "tls.segment.overlap", "tls.segment.overlap.conflict",
        "tls.segment.multiple_tails", "tls.segment.error",
        "tls.record.content_type", "tls.change_cipher_spec",
    ],
    "DNS": [
        "dns", "dns.flags", "dns.flags.opcode", "dns.flags.authoritative",
        "dns.flags.truncated", "dns.flags.recdesired", "dns.flags.recavail",
        "dns.flags.z", "dns.flags.authenticated", "dns.flags.checkdisable",
        "dns.flags.rcode", "dns.id", "dns.count.queries", "dns.count.answers",
        "dns.count.auth_rr", "dns.count.add_rr", "dns.qry.name",
        "dns.qry.type", "dns.qry.class", "dns.resp.name", "dns.resp.type",
        "dns.resp.class", "dns.resp.ttl", "dns.resp.len",
        "dns.a", "dns.aaaa", "dns.cname", "dns.mx", "dns.ns", "dns.ptr",
        "dns.soa.mname", "dns.soa.rname", "dns.txt", "dns.srv.target",
        "dns.srv.port", "dns.srv.weight", "dns.srv.priority",
        "dns.time", "dns.retransmission", "dns.response_in",
        "dns.response_to", "dns.unsolicited",
    ],
    "DHCP": [
        "dhcp", "bootp", "dhcp.type", "dhcp.hw.type", "dhcp.hw.len",
        "dhcp.hops", "dhcp.id", "dhcp.secs", "dhcp.flags",
        "dhcp.flags.broadcast", "dhcp.ciaddr", "dhcp.yiaddr",
        "dhcp.siaddr", "dhcp.giaddr", "dhcp.hw.mac_addr",
        "dhcp.sname", "dhcp.file", "dhcp.cookie",
        "dhcp.option.type", "dhcp.option.length", "dhcp.option.value",
        "dhcp.option.dhcp_message_type", "dhcp.option.subnet_mask",
        "dhcp.option.router", "dhcp.option.domain_name_server",
        "dhcp.option.domain_name", "dhcp.option.broadcast_address",
        "dhcp.option.requested_ip_address", "dhcp.option.ip_address_lease_time",
        "dhcp.option.dhcp_server_id", "dhcp.option.renewal_time",
        "dhcp.option.rebinding_time", "dhcp.option.hostname",
    ],
    "FTP": [
        "ftp", "ftp.request", "ftp.response", "ftp.request.command",
        "ftp.request.arg", "ftp.response.code", "ftp.response.arg",
        "ftp.passive.ip", "ftp.passive.port", "ftp.active.ip",
        "ftp.active.port", "ftp-data",
    ],
    "SMTP/Email": [
        "smtp", "smtp.req", "smtp.rsp", "smtp.req.command",
        "smtp.req.parameter", "smtp.rsp.code", "smtp.rsp.parameter",
        "smtp.data.fragment", "smtp.auth.username", "smtp.auth.password",
        "pop", "pop.request", "pop.response", "pop.request.command",
        "pop.request.parameter", "pop.response.indicator",
        "pop.response.description", "pop.data.fragment",
        "imap", "imap.request", "imap.response", "imap.request.tag",
        "imap.request.command", "imap.response.status",
    ],
    "SSH": [
        "ssh", "ssh.protocol", "ssh.version", "ssh.packet_length",
        "ssh.padding_length", "ssh.message_code", "ssh.kex.cookie",
        "ssh.kex.algorithms", "ssh.kex.server_host_key_algorithms",
        "ssh.kex.encryption_algorithms_client_to_server",
        "ssh.kex.encryption_algorithms_server_to_client",
        "ssh.kex.mac_algorithms_client_to_server",
        "ssh.kex.mac_algorithms_server_to_client",
        "ssh.kex.compression_algorithms_client_to_server",
        "ssh.kex.compression_algorithms_server_to_client",
    ],
    "Telnet": [
        "telnet", "telnet.data", "telnet.cmd", "telnet.subcmd",
    ],
    "SNMP": [
        "snmp", "snmp.version", "snmp.community", "snmp.pdu_type",
        "snmp.request_id", "snmp.error_status", "snmp.error_index",
        "snmp.variable_bindings", "snmp.name", "snmp.value.oid",
        "snmp.value.int", "snmp.value.uint", "snmp.value.str",
        "snmp.value.ipaddr", "snmp.value.counter", "snmp.value.timeticks",
    ],
    "NTP": [
        "ntp", "ntp.flags", "ntp.flags.li", "ntp.flags.vn", "ntp.flags.mode",
        "ntp.stratum", "ntp.poll", "ntp.precision", "ntp.rootdelay",
        "ntp.rootdispersion", "ntp.refid", "ntp.reftime", "ntp.org",
        "ntp.rec", "ntp.xmt", "ntp.keyid", "ntp.mac",
    ],
    "SIP": [
        "sip", "sip.Method", "sip.Status-Line", "sip.Status-Code",
        "sip.r-uri", "sip.from", "sip.from.user", "sip.from.host",
        "sip.to", "sip.to.user", "sip.to.host", "sip.call-id",
        "sip.cseq", "sip.cseq.method", "sip.contact", "sip.contact.user",
        "sip.contact.host", "sip.via", "sip.via.host", "sip.via.port",
        "sip.content-type", "sip.content-length", "sip.user-agent",
        "sip.server", "sip.expires", "sip.max-forwards",
    ],
    "RTP": [
        "rtp", "rtp.v", "rtp.p", "rtp.x", "rtp.cc", "rtp.m", "rtp.pt",
        "rtp.seq", "rtp.timestamp", "rtp.ssrc", "rtp.csrc",
        "rtp.marker", "rtp.payload", "rtp.setup-method",
        "rtp.setup-frame", "rtp.duplicate", "rtp.analysis.sequence_error",
    ],
    "BGP": [
        "bgp", "bgp.type", "bgp.length", "bgp.version", "bgp.my_as",
        "bgp.hold_time", "bgp.identifier", "bgp.opt_params_len",
        "bgp.withdrawn_routes_length", "bgp.total_path_attribute_length",
        "bgp.nlri_prefix", "bgp.nlri_prefix_length", "bgp.next_hop",
        "bgp.origin", "bgp.as_path", "bgp.local_pref", "bgp.atomic_aggregate",
        "bgp.aggregator_as", "bgp.aggregator_origin", "bgp.community_as",
        "bgp.community_value", "bgp.multi_exit_disc",
    ],
    "OSPF": [
        "ospf", "ospf.version", "ospf.msg_type", "ospf.packet_length",
        "ospf.srcrouter", "ospf.area", "ospf.checksum", "ospf.auth.type",
        "ospf.hello.network_mask", "ospf.hello.hello_interval",
        "ospf.hello.router_priority", "ospf.hello.router_dead_interval",
        "ospf.hello.designated_router", "ospf.hello.backup_designated_router",
        "ospf.hello.neighbor", "ospf.dbd.interface_mtu", "ospf.dbd.options",
        "ospf.dbd.flags", "ospf.dbd.dd_sequence", "ospf.lsa.type",
        "ospf.lsa.id", "ospf.lsa.router", "ospf.lsa.sequence",
    ],
    "EIGRP": [
        "eigrp", "eigrp.version", "eigrp.opcode", "eigrp.checksum",
        "eigrp.flags", "eigrp.sequence", "eigrp.acknowledge",
        "eigrp.as", "eigrp.tlv.type", "eigrp.tlv.length",
    ],
    "RIP": [
        "rip", "rip.command", "rip.version", "rip.routing_domain",
        "rip.ip", "rip.netmask", "rip.next_hop", "rip.metric",
        "rip.family", "rip.tag",
    ],
    "VRRP": [
        "vrrp", "vrrp.version", "vrrp.type", "vrrp.vrid", "vrrp.priority",
        "vrrp.count_ip", "vrrp.auth_type", "vrrp.adver_int", "vrrp.checksum",
        "vrrp.ip", "vrrp.auth_string",
    ],
    "HSRP": [
        "hsrp", "hsrp.version", "hsrp.opcode", "hsrp.state", "hsrp.hellotime",
        "hsrp.holdtime", "hsrp.priority", "hsrp.group", "hsrp.reserved",
        "hsrp.auth_data", "hsrp.vip",
    ],
    "MPLS": [
        "mpls", "mpls.label", "mpls.exp", "mpls.bottom", "mpls.ttl",
    ],
    "GRE": [
        "gre", "gre.flags_and_version", "gre.flags.checksum",
        "gre.flags.routing", "gre.flags.key", "gre.flags.sequence_number",
        "gre.flags.strict_source_route", "gre.flags.recursion_control",
        "gre.flags.version", "gre.proto", "gre.checksum",
        "gre.offset", "gre.key", "gre.sequence_number",
    ],
    "IPSec": [
        "esp", "esp.spi", "esp.sequence", "esp.pad_len", "esp.protocol",
        "ah", "ah.next_header", "ah.length", "ah.reserved", "ah.spi",
        "ah.sequence_number", "ah.icv",
        "isakmp", "isakmp.initiator_cookie", "isakmp.responder_cookie",
        "isakmp.next_payload", "isakmp.version", "isakmp.exchange_type",
        "isakmp.flags", "isakmp.message_id", "isakmp.length",
    ],
    "L2TP": [
        "l2tp", "l2tp.type", "l2tp.length", "l2tp.tunnel", "l2tp.session",
        "l2tp.Ns", "l2tp.Nr", "l2tp.offset", "l2tp.avp.hidden",
        "l2tp.avp.mandatory", "l2tp.avp.length", "l2tp.avp.vendor_id",
        "l2tp.avp.type", "l2tp.tie_breaker", "l2tp.sid",
    ],
    "PPP": [
        "ppp", "ppp.address", "ppp.control", "ppp.protocol",
        "ppp.direction", "pppoed.type", "pppoed.code", "pppoed.session_id",
        "pppoed.length", "pppoes.type", "pppoes.code", "pppoes.session_id",
        "pppoes.length", "lcp", "lcp.code", "lcp.identifier",
        "lcp.length", "lcp.option.type", "lcp.option.length",
    ],
    "Radius": [
        "radius", "radius.code", "radius.id", "radius.length",
        "radius.authenticator", "radius.framed_ip_address",
        "radius.user_name", "radius.user_password", "radius.chap_password",
        "radius.nas_ip_address", "radius.nas_port", "radius.service_type",
        "radius.framed_protocol", "radius.framed_mtu", "radius.login_service",
    ],
    "802.11 WiFi": [
        "wlan", "wlan.fc.type", "wlan.fc.subtype", "wlan.fc.ds",
        "wlan.fc.tods", "wlan.fc.fromds", "wlan.fc.frag", "wlan.fc.retry",
        "wlan.fc.pwrmgt", "wlan.fc.moredata", "wlan.fc.protected",
        "wlan.duration", "wlan.ra", "wlan.da", "wlan.ta", "wlan.sa",
        "wlan.bssid", "wlan.addr", "wlan.frag", "wlan.seq",
        "wlan.bar.control", "wlan.ba.control", "wlan.qos.priority",
        "wlan.qos.eosp", "wlan.qos.ack", "wlan.qos.amsdupresent",
        "wlan_mgt", "wlan_mgt.beacon", "wlan_mgt.probereq", "wlan_mgt.proberesp",
        "wlan_mgt.assocreq", "wlan_mgt.assocresp", "wlan_mgt.reassocreq",
        "wlan_mgt.reassocresp", "wlan_mgt.disassoc", "wlan_mgt.auth",
        "wlan_mgt.deauth", "wlan_mgt.ssid", "wlan_mgt.supported_rates",
        "wlan_mgt.ds.current_channel", "wlan_mgt.tim", "wlan_mgt.country_info",
        "wlan_mgt.rsn", "wlan_mgt.rsn.version", "wlan_mgt.rsn.gcs.type",
        "wlan_mgt.rsn.pcs.type", "wlan_mgt.rsn.akms.type",
    ],
    "LLDP": [
        "lldp", "lldp.tlv.type", "lldp.tlv.len", "lldp.chassis_id.subtype",
        "lldp.chassis_id", "lldp.port_id.subtype", "lldp.port_id",
        "lldp.time_to_live", "lldp.port_description", "lldp.system_name",
        "lldp.system_description", "lldp.system_capabilities",
        "lldp.system_capabilities_enabled", "lldp.management_address",
        "lldp.organization_specific_oui", "lldp.dcbx.feature.type",
        "lldp.ieee.802_1.port_vlan_id", "lldp.ieee.802_1.vlan_name",
        "lldp.ieee.802_3.mac_phy_config_status", "lldp.ieee.802_3.power_via_mdi",
        "lldp.ieee.802_3.link_aggregation", "lldp.ieee.802_3.max_frame_size",
    ],
    "STP": [
        "stp", "stp.protocol", "stp.version", "stp.type", "stp.flags",
        "stp.root.hw", "stp.root.cost", "stp.bridge", "stp.port",
        "stp.msg_age", "stp.max_age", "stp.hello_time", "stp.forward_delay",
        "stp.version_1_length", "mstp.version_3_length", "mstp.config_id",
        "mstp.config_name", "mstp.revision_level", "mstp.config_digest",
        "mstp.cist_internal_root_path_cost", "mstp.cist_bridge",
        "mstp.cist_remaining_hops", "rstp.flags", "rstp.flags.tc",
        "rstp.flags.agreement", "rstp.flags.forwarding", "rstp.flags.learning",
        "rstp.flags.port_role", "rstp.flags.proposal", "rstp.flags.tc_ack",
    ],
    "LACP": [
        "lacp", "lacp.version", "lacp.actor_type", "lacp.actor_info_len",
        "lacp.actor.sys_priority", "lacp.actor.sys", "lacp.actor.key",
        "lacp.actor.port_priority", "lacp.actor.port", "lacp.actor.state",
        "lacp.flags.activity", "lacp.flags.timeout", "lacp.flags.aggregation",
        "lacp.flags.synchronization", "lacp.flags.collecting",
        "lacp.flags.distributing", "lacp.flags.defaulted", "lacp.flags.expired",
        "lacp.partner_type", "lacp.partner_info_len", "lacp.partner.sys_priority",
        "lacp.partner.sys", "lacp.partner.key", "lacp.partner.port_priority",
        "lacp.partner.port", "lacp.partner.state", "lacp.collector_type",
        "lacp.collector_info_len", "lacp.collector.max_delay",
    ],
    "NetFlow": [
        "cflow", "cflow.version", "cflow.count", "cflow.sysuptime",
        "cflow.timestamp", "cflow.unix_secs", "cflow.unix_nsecs",
        "cflow.sequence", "cflow.engine_type", "cflow.engine_id",
        "cflow.sampling_interval", "cflow.srcaddr", "cflow.dstaddr",
        "cflow.nexthop", "cflow.input_snmp", "cflow.output_snmp",
        "cflow.dPkts", "cflow.dOctets", "cflow.first", "cflow.last",
        "cflow.srcport", "cflow.dstport", "cflow.prot", "cflow.tos",
        "cflow.tcp_flags", "cflow.src_as", "cflow.dst_as",
        "cflow.src_mask", "cflow.dst_mask",
    ],
    "sFlow": [
        "sflow", "sflow.version", "sflow.agent_address_type", "sflow.agent_address",
        "sflow.sub_agent_id", "sflow.sequence_number", "sflow.sysuptime",
        "sflow.numsamples", "sflow.sample_type", "sflow.sample_length",
        "sflow.sample_sequence_number", "sflow.sampling_rate", "sflow.sample_pool",
        "sflow.drops", "sflow.input_interface", "sflow.output_interface",
        "sflow.flow_sample", "sflow.counter_sample",
    ],
}

# Common filter examples for quick reference
FILTER_EXAMPLES = [
    # Basic filtering
    "tcp.port == 80",
    "tcp.port == 443",
    "udp.port == 53",
    "ip.addr == 192.168.1.1",
    "ip.src == 10.0.0.1",
    "ip.dst == 192.168.1.100",
    "eth.addr == 00:11:22:33:44:55",
    
    # Protocol filtering
    "tcp", "udp", "icmp", "dns", "http", "https", "ssh", "ftp",
    "arp", "dhcp", "smtp", "pop", "imap", "snmp", "ntp",
    
    # Advanced TCP analysis
    "tcp.flags.syn == 1 && tcp.flags.ack == 0",
    "tcp.flags.reset == 1",
    "tcp.analysis.retransmission",
    "tcp.analysis.duplicate_ack",
    "tcp.analysis.zero_window",
    "tcp.analysis.out_of_order",
    "tcp.len > 0",
    "tcp.stream == 0",
    
    # HTTP/HTTPS analysis
    "http.request.method == GET",
    "http.request.method == POST",
    "http.response.code == 200",
    "http.response.code >= 400",
    "http.host contains google.com",
    "http.user_agent contains Mozilla",
    "tls.handshake.type == 1",
    "ssl.record.version == 0x0303",
    
    # DNS analysis
    "dns.qry.name contains google",
    "dns.flags.rcode != 0",
    "dns.qry.type == 1",
    "dns.qry.type == 28",
    "dns.response_in",
    
    # Network troubleshooting
    "icmp.type == 3",
    "icmp.type == 11",
    "arp.duplicate-address-detected",
    "tcp.analysis.retransmission and tcp.analysis.fast_retransmission",
    "frame.len > 1514",
    "ip.fragment",
    "tcp.checksum_bad",
    "udp.checksum_bad",
    
    # Security analysis
    "tcp.flags.syn == 1 and tcp.window_size < 1024",
    "ip.ttl < 64",
    "tcp.port in {1433 3389 5900 23}",
    "dns.qry.name matches \".*(exe|bat|scr|com|pif)$\"",
    "http.request.uri contains script",
    "tls.alert.description == 21",
    
    # Performance analysis
    "tcp.time_delta > 0.1",
    "tcp.analysis.ack_rtt > 0.5",
    "http.time > 5",
    "dns.time > 1",
    "frame.time_delta > 1",
    
    # WiFi analysis
    "wlan.fc.type == 0",
    "wlan.fc.type == 1",
    "wlan.fc.type == 2",
    "wlan_mgt.beacon",
    "wlan_mgt.deauth",
    
    # VoIP analysis
    "sip",
    "rtp",
    "sip.Method == INVITE",
    "sip.Status-Code >= 400",
    "rtp.pt == 0",
    
    # Routing protocols
    "ospf",
    "bgp",
    "eigrp",
    "rip",
    "ospf.msg_type == 1",
    "bgp.type == 2",
    
    # Network management
    "snmp",
    "lldp",
    "stp",
    "lacp",
    "snmp.version == 2",
    "lldp.tlv.type == 1",
    
    # Tunneling protocols
    "gre",
    "l2tp",
    "esp",
    "ah",
    "pptp",
    "mpls",
    
    # Complex combinations
    "tcp.port == 80 and http.request.method == GET",
    "udp.port == 53 and dns.flags.rcode == 3",
    "ip.addr == 192.168.1.0/24 and tcp.flags.syn == 1",
    "not arp and not icmp and not dns",
    "tcp.len > 0 and not tcp.analysis.keep_alive",
    "(tcp.port == 80 or tcp.port == 443) and http",
    "ip.src == 10.0.0.0/8 or ip.src == 192.168.0.0/16 or ip.src == 172.16.0.0/12",
]
